project:
  type: website
  output-dir: docs
website:
  title: "Tanisha's Webiste"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: My Projects
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



